import pathlib

src   = pathlib.Path('main.py').read_text(encoding='utf-8')
lines = src.splitlines(keepends=True)
print(f'Total lines: {len(lines)}')

R = []
def a(s): R.append(s + '\n')

a('    # -- Read per-employee monitoring settings ---------------------------------')
a('    monitoring = {')
a('        "clipboard": user_info.get("monitor_clipboard", True),')
a('        "usb":       user_info.get("monitor_usb",       True),')
a('        "webmail":   user_info.get("monitor_webmail",   True),')
a('        "file_scan": user_info.get("monitor_file_scan", True),')
a('    }')
a('    disabled = [k.upper() for k, v in monitoring.items() if not v]')
a('    if disabled:')
a('        print("[*] Channels DISABLED by admin: " + ", ".join(disabled))')
a('    else:')
a('        print("[*] All monitoring channels enabled for this account.")')
a('')
a('    clipboard_monitor = None')
a('    usb_monitor       = None')
a('    webmail_server    = None')
a('')
a('    if monitoring["clipboard"]:')
a('        try:')
a('            from comms.clipboard_monitor import ClipboardMonitor')
a('            clipboard_monitor = ClipboardMonitor(bg_state, on_finding_callback=_bg_event)')
a('            clipboard_monitor.start()')
a('            print("[*] Clipboard monitor active.")')
a('        except Exception as e:')
a('            print("[*] Clipboard monitor unavailable:", e)')
a('    else:')
a('        print("[*] Clipboard monitor DISABLED by admin policy.")')
a('')
a('    if monitoring["usb"]:')
a('        try:')
a('            from comms.usb_watcher import USBWatcher')
a('            usb_monitor = USBWatcher(bg_state, on_report_callback=None, on_event_callback=_bg_event)')
a('            usb_monitor.start()')
a('            print("[*] USB watcher active.")')
a('        except Exception as e:')
a('            print("[*] USB watcher unavailable:", e)')
a('    else:')
a('        print("[*] USB watcher DISABLED by admin policy.")')
a('')
a('    if monitoring["webmail"]:')
a('        try:')
a('            from comms.http_server import DataShieldHTTPServer')
a('            webmail_server = DataShieldHTTPServer(bg_state, on_event_callback=_bg_event)')
a('            webmail_server.start()')
a('            print("[*] Webmail scan API active on port 5000.")')
a('        except Exception as e:')
a('            print("[*] Webmail HTTP server unavailable:", e)')
a('    else:')
a('        print("[*] Webmail monitor DISABLED by admin policy.")')
a('')
a('    # Step 4: System tray')
a('    run_system_tray(name, email)')
a('')
a('    # Step 5: Employee home window')
a('    try:')
a('        from gui.main_window import EmployeeHomeWindow')
a('')
a('        def _do_logout():')
a('            print("[*] Employee logged out.")')
a('            for mon in [clipboard_monitor, usb_monitor]:')
a('                if mon:')
a('                    try: mon.stop()')
a('                    except Exception: pass')
a('            if webmail_server:')
a('                try: webmail_server.stop()')
a('                except Exception: pass')
a('            if client:')
a('                try: client.stop()')
a('                except Exception: pass')
a('            import subprocess')
a('            subprocess.Popen([sys.executable] + sys.argv)')
a('            sys.exit(0)')
a('')
a('        app = EmployeeHomeWindow(')
a('            user_name=name,')
a('            user_email=email,')
a('            monitors=monitoring,')
a('            server_url=server_url,')
a('            logout_callback=_do_logout,')
a('        )')
a('        if client:')
a('            app.state["reporting_client"] = client')
a('        bg_state["root_window"] = app')
a('        _tray_state["main_window"] = app')
a('')
a('        def _on_close():')
a('            app.withdraw()')
a('            alerts.send_desktop_notification(')
a('                "DataShield",')
a('                "Still protecting your workstation in the background.")')
a('        app.protocol("WM_DELETE_WINDOW", _on_close)')
a('')
a('        _orig_bg = _bg_event')
a('        def _bg_event_with_feed(channel, action, detail, decision=None, **kwargs):')
a('            _orig_bg(channel, action, detail, decision=decision, **kwargs)')
a('            if action in ("ALLOW", "LOG"):')
a('                return')
a('            rl = "HIGH"')
a('            if decision and hasattr(decision, "risk_level"):')
a('                rl = decision.risk_level')
a('            elif action == "WARN":')
a('                rl = "MEDIUM"')
a('            pattern = getattr(decision, "top_pattern", "") if decision else ""')
a('            app.after(0, lambda c=channel, a=action, d=detail, r=rl, p=pattern:')
a('                       app.push_threat(c, a, d, r, p))')
a('')
a('        if clipboard_monitor and hasattr(clipboard_monitor, "on_finding_callback"):')
a('            clipboard_monitor.on_finding_callback = _bg_event_with_feed')
a('        if usb_monitor and hasattr(usb_monitor, "on_event_callback"):')
a('            usb_monitor.on_event_callback = _bg_event_with_feed')
a('        if webmail_server and hasattr(webmail_server, "on_event_callback"):')
a('            webmail_server.on_event_callback = _bg_event_with_feed')
a('')
a('        def _ping_server():')
a('            online = False')
a('            if server_url:')
a('                try:')
a('                    import httpx as _hx')
a('                    resp = _hx.get(server_url + "/api/health", timeout=3)')
a('                    online = resp.status_code < 500')
a('                except Exception:')
a('                    online = False')
a('            app.set_agent_status(online)')
a('            app.after(30000, _ping_server)')
a('')
a('        app.after(2000, _ping_server)')
a('')
a('        print("[*] DataShield running. Opening employee portal...")')
a('        first_name = name.split()[0] if name else "there"')
a('        alerts.send_desktop_notification(')
a('            "DataShield Active",')
a('            "Hello " + first_name + "! Your workstation is now protected.")')
a('        app.deiconify()')
a('        app.mainloop()')
a('')

new_lines = lines[:584] + R + lines[679:]
result = ''.join(new_lines)
pathlib.Path('main.py').write_text(result, encoding='utf-8')
print('Written.')

import ast
try:
    ast.parse(result)
    print('SYNTAX OK - all done!')
except SyntaxError as e:
    print('SYNTAX ERROR line', e.lineno, ':', e.msg)
    sl = result.splitlines()
    lo = max(0, e.lineno - 4)
    hi = min(len(sl), e.lineno + 3)
    for i, l in enumerate(sl[lo:hi], lo + 1):
        marker = '>>>' if i == e.lineno else '   '
        print(marker, i, ':', l)
